// The walk of LZMA (`packages/codecs/src/lzma.ts`), against streams Python's own `lzma` module wrote: an
// implementation of that format other than this port's own stands behind every count below, of both shapes of
// the stream and of the properties of the counts of their own.
import { Buffer } from "node:buffer";
import {
	decompressLzmaAlone,
	decompressLzmaRaw,
	decompressLzmaZip,
	readLzmaProperties,
	writeLzmaProperties,
} from "@garbro-mcp/codecs";
import { describe, expect, it } from "vitest";

/** The properties every stream of Python's own preset six stands of: `lc` three, `lp` nought, `pb` two. */
const PROPERTIES = {
	lc: 3,
	lp: 0,
	pb: 2,
	dictionarySize: 1 << 20,
};

interface Case {
	name: string;
	alone: string;
	raw: string;
	plain: string;
}

const CASES: Case[] = [
	{
		name: "a file of the places of the file of the walk of the counts of them",
		alone:
			"XQAAgAD//////////wA6GgjOdr6zr5aYV2J7UohT+0O0tTCR1VhGR9zksau2gjW2YLBhbVKPqDPm7gBVqf//+ZAAAA==",
		raw: "ADoaCM52vrOvlphXYntSiFP7Q7S1MJHVWEZH3OSxq7aCNbZgsGFtUo+oM+buAFWp///5kAAA",
		plain:
			"dGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0KdGhlIHBsYWNlcyBvZiB0aGUgZmlsZSBvZiB0aGUgd2FsayBvZiB0aGUgY291bnRzIG9mIHRoZW0K",
	},
	{
		name: "a file of one place of the file",
		alone: "XQAAgAD//////////wAgwfv////gAAAA",
		raw: "ACDB+////+AAAAA=",
		plain: "QQ==",
	},
	{
		name: "a file of no places of the file at all",
		alone: "XQAAgAD//////////wCD//v//8AAAAA=",
		raw: "AIP/+///wAAAAA==",
		plain: "",
	},
	{
		name: "a file of every place of the file of an engine",
		alone:
			"XQAAgAD//////////wAAAFJQCoT5m7KAIalp1ifgPgZaXwSNU9QEujlXBQnBVSTenbhxWTFgoZ/5b0lz8sjqjLoaiylpIYD+M4Nmr0Zt7J6JiguD8DwOiY4/7V/nnpDZHP8y9LLgOVGy0hQVtMVxutsG43man7s4wbAArJMLqgYZAxIIFVubyEjwMi7+LaCHyPCk4NJR641nVpKyTYTF8YYx32piW8J5Ldn3PHO6dHQH2DypViIkoWb4WoRfMGfS9ktJLn8g69v4EA6UeHfHP2vvtM2V4m/2RG4GzwuCGsvbevBXjZj/kMA+5sESQXXuAyiW6xP7pyjMrzK7pA4l8lY8+BqH//7tT6A=",
		raw: "AAAAUlAKhPmbsoAhqWnWJ+A+BlpfBI1T1AS6OVcFCcFVJN6duHFZMWChn/lvSXPyyOqMuhqLKWkhgP4zg2avRm3snomKC4PwPA6Jjj/tX+eekNkc/zL0suA5UbLSFBW0xXG62wbjeZqfuzjBsACskwuqBhkDEggVW5vISPAyLv4toIfI8KTg0lHrjWdWkrJNhMXxhjHfamJbwnkt2fc8c7p0dAfYPKlWIiShZvhahF8wZ9L2S0kufyDr2/gQDpR4d8c/a++0zZXib/ZEbgbPC4Iay9t68FeNmP+QwD7mwRJBde4DKJbrE/unKMyvMrukDiXyVjz4Gof//u1PoA==",
		plain:
			"AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/wABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8AAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXp7fH1+f4CBgoOEhYaHiImKi4yNjo+QkZKTlJWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6u7y9vr/AwcLDxMXGx8jJysvMzc7P0NHS09TV1tfY2drb3N3e3+Dh4uPk5ebn6Onq6+zt7u/w8fLz9PX29/j5+vv8/f7/AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/wABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8AAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXp7fH1+f4CBgoOEhYaHiImKi4yNjo+QkZKTlJWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6u7y9vr/AwcLDxMXGx8jJysvMzc7P0NHS09TV1tfY2drb3N3e3+Dh4uPk5ebn6Onq6+zt7u/w8fLz9PX29/j5+vv8/f7/AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/wABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8=",
	},
	{
		name: "a file of one place of the file of five thousand of them",
		alone:
			"XQAAgAD//////////wAAb/3//6O3/0c+SBVyOWFRuJIo5qOGB/nuzdTUJh///YRAAA==",
		raw: "AABv/f//o7f/Rz5IFXI5YVG4kijmo4YH+e7N1NQmH//9hEAA",
		plain:
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
	},
];

describe("LZMA streams", () => {
	it("reads the five bytes of the properties of a stream, and writes them back", () => {
		// The first byte stands of `(pb * 5 + lp) * 9 + lc`, which is 0x5D for the counts above.
		const bytes = Buffer.from("5d00008000", "hex");
		expect(readLzmaProperties(bytes)).toEqual({
			...PROPERTIES,
			dictionarySize: 0x00800000,
		});
		expect(
			writeLzmaProperties({ ...PROPERTIES, dictionarySize: 0x00800000 }).equals(
				bytes,
			),
		).toBe(true);
		expect(readLzmaProperties(Buffer.alloc(4, 0x00))).toBeUndefined();
		// A count of the places of the file past its own.
		expect(
			readLzmaProperties(Buffer.from("ff00000000", "hex")),
		).toBeUndefined();
	});

	it("reads a stream of the shape of LZMA alone, of the count of its own places open", () => {
		// Every case but the empty file: a stream of an empty file of no count of its own holds no end
		// marker the walk of the engine can reach, which the test below stands of.
		for (const item of CASES.filter((entry) => 0 !== entry.plain.length)) {
			const plain = Buffer.from(item.plain, "base64");
			expect(
				decompressLzmaAlone(Buffer.from(item.alone, "base64")).equals(plain),
			).toBe(true);
		}
	});

	it("reads a stream of LZMA alone of the count of its own places written", () => {
		// The same stream, of its head rewritten to carry the count of the places of the file of its own.
		const plain = Buffer.from(CASES[0]?.plain ?? "", "base64");
		const alone = Buffer.from(CASES[0]?.alone ?? "", "base64");
		const sized = Buffer.from(alone);
		sized.writeBigUInt64LE(BigInt(plain.length), 5);
		expect(decompressLzmaAlone(sized).equals(plain)).toBe(true);
	});

	it("reads a stream of the counts of the places of the file the caller names", () => {
		for (const item of CASES) {
			const plain = Buffer.from(item.plain, "base64");
			expect(
				decompressLzmaRaw(
					Buffer.from(item.raw, "base64"),
					PROPERTIES,
					plain.length,
				).equals(plain),
			).toBe(true);
		}
	});

	it("reads a stream of no places of the file at all, of the count of its own places named", () => {
		// The count of the places of the file is what a stream of none of them stands of: the same bytes of
		// the walk of the engine, read of a count of nought, stand of no places of the file at all.
		expect(decompressLzmaRaw(Buffer.alloc(0, 0x00), PROPERTIES, 0).length).toBe(
			0,
		);
		// And a stream of the shape of LZMA alone whose count stands open holds no end marker for an empty
		// file, which is where the walk of the reference stands and stands of no count of its own: Python's
		// own reader stops at the end of the places of the file of the stream instead.
		const empty = Buffer.from(CASES[2]?.alone ?? "", "base64");
		expect(() => decompressLzmaAlone(empty)).toThrow(/lzma/);
	});

	it("reads the payload of a ZIP entry of the fourteenth method", () => {
		const payload = Buffer.from(
			"CQQFAF0AABAAACDofc/A9pBqG+SdGz8jjtFNuTUTh8ZmQ5etyQ/b//8WwAAA",
			"base64",
		);
		const plain = Buffer.from(
			"QUFBQQd6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCB6aXAgbHptYSBwYXlsb2FkIHppcCBsem1hIHBheWxvYWQgemlwIGx6bWEgcGF5bG9hZCA=",
			"base64",
		);
		expect(decompressLzmaZip(payload, plain.length).equals(plain)).toBe(true);
	});

	it("turns away a stream that stands short or of a place of a match beyond its own", () => {
		const alone = Buffer.from(CASES[0]?.alone ?? "", "base64");
		expect(() => decompressLzmaAlone(alone.subarray(0, 12))).toThrow(
			/short of its own head/,
		);
		expect(() => decompressLzmaAlone(alone.subarray(0, 20))).toThrow(/lzma/);
		// A place of the file of the walk of the engine set to noise, so the stream reads beyond its output.
		const broken = Buffer.from(alone);
		broken[30] = (broken[30] ?? 0) ^ 0xff;
		expect(() => decompressLzmaAlone(broken)).toThrow(/lzma/);
		expect(() => decompressLzmaZip(Buffer.alloc(4, 0x00), 10)).toThrow(
			/short of its own head/,
		);
	});
});
